server:
  port: 9001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080

  datasource:
    driver-class-n  ame: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/user?characterEncoding=utf-8&useUnicode&serverTimezone=UTC
    username: root
    password: kang123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 4
      max-active: 20
      max-wait: 3000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_

      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
      id-type: id_worker

  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.abu.mpboot.pojo




